import React from 'react'
import ForgotPassword from '../Componets/ForgotPassword'

export const metadata = {
  title: "Forgot Password",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <ForgotPassword/>
    </>
  )
}
