import React from 'react'
import ShoppingCart from '../Componets/ShoppingCart'

export const metadata = {
  title: "Cart ",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <ShoppingCart/>
    </>
  )
}
