import "./assets/style.css";
import Footer from "./Componets/Common/Footer";
import Header from "./Componets/Common/Header";
import Providers from "./Providers";


export const metadata = {
  title: "Monsta",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Header />
          {children}
          <script async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9387062363004258"
            crossorigin="anonymous"></script>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
