import "./assets/style.css";
import Footer from "./Componets/Common/Footer";
import Header from "./Componets/Common/Header";
import Providers from "./Providers";


export const metadata = {
  title: "Monsta || Next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Providers>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
