import React from 'react'
import Login from '../Componets/Login'

export const metadata = {
  title: "Login / Register ",
  description: "Generated by create next app",
};


export default function page() {
    return (
        <div>
            <Login />
        </div>
    )
}
