import React from 'react'
import FAQS from '../Componets/FAQS'

export const metadata = {
  title: "FAQS",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <FAQS/>
    </>
  )
}
