import React from 'react'
import Dashboard from '../Componets/Dashboard'

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <Dashboard/>
    </>
  )
}
