import React from 'react'
import OnlineStore from '../Componets/OnlineStore'

export const metadata = {
  title: "Online Store",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <>
    <OnlineStore/>
    </>
  )
}
