import React from 'react'
import ProductsList from '../Componets/ProductsList'

export const metadata = {
  title: "Categories ",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
    <ProductsList/>
    </>
  )
}
