import React from 'react'
import ContactUs from '../Componets/ContactUs'

export const metadata = {
  title: "Contact Us",
  description: "Generated by create next app",
};


export default function page() {
  return (
    <div>
        <ContactUs/>
    </div>
  )
}
